config/routes.rb
Rails.application.routes.draw do
  resources :people
  root 'people#index'
end

app/models/person.rb
class Person < ActiveRecord::Base
  mount_uploader :picture, AvatarUploader
  GENDERS = [ 'female', "male"]

  validates :bio, length: { maximum: 500 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 254 }
  validates :first_name, presence: true, length: { maximum: 75 }
  validates :job, length: { maximum: 75 }
  validates :gender, presence: true, inclusion: { in: GENDERS }
  validates :last_name, presence: true, length: { maximum: 75 }
  validates :birthdate, presence: true
  validates_date :birthdate, on_or_before: lambda { Date.current }

  scope :order_by_full_name, -> { order('first_name', 'last_name') }

  def full_name
    "#{first_name} #{last_name}"
  end

  def age
    (Date.today - birthdate).to_i / 365
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    load_people
  end

  def show
    load_person
  end

  def new
    build_person
  end

  def create
    build_person
    save_person or render :new
  end

  def edit
    load_person
    build_person
  end

  def update
    load_person
    build_person
    save_person or render :edit
  end

  def destroy
    load_person
    @person.destroy
    NotifyJob.perform_later(action: 'destroy', person: @person.full_name)
    flash[:notice] = "Person deleted successfuly"
    redirect_to people_path
  end

  private
    def load_people
      @q = people_scope.ransack(params[:q])
      @people ||= @q.result(distinct: true).paginate(page: params[:page])
    end

    def load_person
      @person ||= people_scope.find(params[:id])
    end

    def build_person
      @person ||= people_scope.build
      @person.attributes = person_params
    end

    def save_person
      if @person.save
        flash[:notice] = "Person saved successfuly"
        NotifyJob.perform_later(action: 'create', person: @person) if action_name == 'create'
        redirect_to @person
      else
        flash[:error] = @person.errors.full_messages.to_sentence
        false
      end
    end

    def person_params
      person_params = params[:person]
      person_params ? person_params.permit(:first_name, :last_name, :email, :bio, :gender, :job, :birthdate, :picture) : {}
    end

    def people_scope
      Person.order_by_full_name.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <title>People Manager</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.1/material.min.js"></script>
    <%= csrf_meta_tags %>
    <style>
    </style>
  </head>
  <body class="mdl-demo mdl-color--grey-100 mdl-color-text--grey-700 mdl-base">
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header mdl-layout__header--scroll mdl-color--primary">
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
        </div>
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
          <h3> People Manager </h3>
        </div>
        <div class="mdl-layout--large-screen-only mdl-layout__header-row">
        </div>
        <div class="mdl-layout__tab-bar mdl-js-ripple-effect mdl-color--primary-dark">
          <%= link_to 'People', people_path, class: "mdl-layout__tab is-active" %> 
        </div>
      </header>
      <main class="mdl-layout__content">
      <div class="mdl-layout__tab-panel is-active">
        <%= yield %>
      </div>
      <footer class="mdl-mega-footer">
        <div class="mdl-mega-footer--middle-section">
        </div>
        <div class="mdl-mega-footer--bottom-section">
          <div class="mdl-logo">
            luisk hernandez
          </div>
        </div>
      </footer>
      </main>
    </div>
  </body>
</html>

app/views/people/_form.html.erb
<div class="mdl-card mdl-shadow--6dp full-width">
  <div class="mdl-card__title mdl-color--primary mdl-color-text--white">
    <h2 class="mdl-card__title-text"> <%= action_name.capitalize %> Person</h2>
  </div>
  <div class="mdl-card__supporting-text">
    <%= form_for @person, multipart: true,html: { class: 'colum-form full-width text-center' } do |f| %>
      <div>
        <%= image_tag 'avatar.png', class: 'image_to_upload' %>
        <%= f.file_field :picture %>
      </div>
      <div class="mdl-textfield mdl-js-textfield">
        <%= f.label :first_name, class: 'mdl-textfield__label' %>
        <%= f.text_field :first_name, class: 'mdl-textfield__input' %>
      </div>
      <div class="mdl-textfield mdl-js-textfield">
        <%= f.label :last_name, class: 'mdl-textfield__label' %>
        <%= f.text_field :last_name, class: 'mdl-textfield__input' %>
      </div>
      <div class="mdl-textfield mdl-js-textfield">
        <%= f.label :email, class: 'mdl-textfield__label' %>
        <%= f.text_field :email, class: 'mdl-textfield__input' %>
      </div>
      <div class="mdl-textfield mdl-js-textfield">
        <%= f.label :job, class: 'mdl-textfield__label' %>
        <%= f.text_field :job, class: 'mdl-textfield__input' %>
      </div>
      <div class="mdl-textfield mdl-selectfield">
        <%= f.label :gender %>
        <%= f.select :gender, Person::GENDERS, class: 'browser-default' %>
      </div>
      <div class="mdl-textfield mdl-js-textfield">
        <%= f.label :birthdate, class: 'mdil-textfield__label' %>
        <%= f.date_field :birthdate, class: 'mdl-textfield__input' %>
      </div>
      <div class="mdl-textfield mdl-js-textfield mdl-texarea">
        <%= f.label :bio, class: 'mdl-textfield__label' %>
        <%= f.text_area :bio, class: 'mdl-textfield__input ' %>
      </div>
  </div>
  <div class="mdl-card__actions mdl-card--border">
    <div class="push-right">
      <%= link_to 'Cancel', people_path, class: "mdl-button mdl-js-button mdl-button--raised mdl-button--accent"   %>
      <%= f.submit "Save", class: "mdl-button mdl-js-button mdl-button--raised mdl-button--colored" %>
    </div>
  </div>
<% end %>
</div>

app/views/people/_person.html.erb
<tr>
  <td><%= link_to person.full_name, person %></td>
  <td><%= person.email %></td>
  <td><%= person.age %></td>
  <td><%= link_to "Delete", person,
    method: :delete,
    class: 'mdl-button mdl-js-button mdl-button--raised mdl-button--accent',
    data: { confirm: "Are you sure ? .This action will remove #{person.full_name} from the sytem. "} %></td>
</tr>

app/views/people/edit.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <%= render partial: 'form' %>
</section>

app/views/people/index.html.erb
<%= link_to new_person_path, class: "fixed-button mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored mdl-shadow--4dp mdl-color--accent" do  %>
  <i class="material-icons" role="presentation">add</i>
  <span class="visuallyhidden">Add</span>
<% end %>

<%= search_form_for @q do |f|  %>
  <i class="material-icons">search</i>
  <div class="mdl-textfield mdl-js-textfield">
    <%= f.label :first_name_or_last_name_or_email_cont, class: 'mdl-textfield__label' %>
    <%= f.text_field :first_name_or_last_name_or_email_cont, class: 'mdl-textfield__input' %>
  </div>
      <%  if params[:q]%>
        <%= link_to 'Clear', people_path %>
      <% end %>
<% end %>

<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <table class="mdl-data-table full-table">
    <thead>
      <tr>
        <th>
          <%= will_paginate @people %>
        </th>
      </tr>
      <tr>
        <th> <%= sort_link(@q, :first_name, 'Full Name', default_order: {last_name: 'asc', first_name: 'asc'}) %> </th>
        <th> <%= sort_link(@q, :email) %> </th>
        <th> <%= sort_link(@q, :birthdate, 'Age', hide_indicator: true) %></th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <%= render @people %>
    </tbody>
  </table>
</section>

app/views/people/new.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
  <%= render partial: 'form' %>
</section>

app/views/people/show.html.erb
<section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp profile">
  <section class="section--center mdl-grid mdl-grid--no-spacing mdl-shadow--2dp">
    <header class="section__play-btn mdl-cell mdl-cell--3-col-desktop mdl-cell--2-col-tablet mdl-cell--4-col-phone mdl-color-text--white">
      <%= image_tag @person.picture.url || 'avatar.png' %>
    </header>
    <div class="mdl-card mdl-cell mdl-cell--9-col-desktop mdl-cell--6-col-tablet mdl-cell--4-col-phone">
      <div class="mdl-card__supporting-text">
        <h4><%= @person.full_name %></h4>
        <ul class="mdl-list ul-vertical">
          <li class="mdl-list__item">Age: <%= @person.age %></li>
          <li class="mdl-list__item">Gender: <%= @person.gender %></li>
          <li class="mdl-list__item">Job: <%= @person.job %></li>
        </ul>
        <p> <%= @person.bio %></p>
      </div>
      <div class="mdl-card__actions">
        <%= link_to "Edit info", edit_person_path(@person), class: 'mdl-button  mdl-button--accent' %>
        <%= link_to "Delete", @person, method: :delete,
          data: { confirm: "Are you sure ? .This action will remove #{@person.full_name} from the sytem. "},
          class: 'mdl-button' %>
      </div>
    </div>
  </section>
</section>